site_name: Maverick Render Documentation
site_url: https://maverickrender.com/wp-content/docs/
copyright: (c) 2001-2017 Chema Guerra and (c) 2018-2025 RandomControl SL. All Rights Reserved.
use_directory_urls: false
nav:
  - index.md
  - CLI: CLI/index.md
  - Python: Python/index.md
  - Nodes:
    - Global:
        - 'Globals':             Nodes/Global/globals.md
        - 'AOVs':                Nodes/Global/aovs.md
        - 'Tone mapping':        Nodes/Global/tonemap.md
        - 'LightMixer':          Nodes/Global/lightmixer.md
        - 'IBL':                 Nodes/Global/ibl.md
        - 'Sky':                 Nodes/Global/sky.md
    - Camera:
        - 'Perspective':         Nodes/Camera/cam_persp.md
        - 'VR':                  Nodes/Camera/cam_vr.md
    - Object:
        - 'Assembly':            Nodes/Object/obj_assembly.md
        - 'Light':               Nodes/Object/obj_light.md
        - 'Point Cloud':         Nodes/Object/obj_points.md
        - 'Polygon Mesh':        Nodes/Object/obj_polymesh.md
        - 'Primitive':           Nodes/Object/obj_primitive.md
        - 'Target':              Nodes/Object/obj_target.md
    - Modifier:
        - 'Multi-Clone':         Nodes/Modifier/mod_multiclone.md
        - 'Scatter':             Nodes/Modifier/mod_scatter.md
        - 'Sticker':             Nodes/Modifier/mod_sticker.md
        - 'UV Map':              Nodes/Modifier/mod_uvmap.md
    - Material:
      - Main:
        - 'Standard':            Nodes/Material/Main/mtl_standard.md
        - 'Blend':               Nodes/Material/Main/mtl_blend.md
        - 'Shadow Catcher':      Nodes/Material/Main/mtl_shadow_catcher.md
      - Derived:
        - 'Emissive':            Nodes/Material/Derived/mtl_emissive.md
        - 'Emissive (Coated)':   Nodes/Material/Derived/mtl_emissive_coated.md
        - 'Gemstone':            Nodes/Material/Derived/mtl_gemstone.md
        - 'Glass':               Nodes/Material/Derived/mtl_glass.md
        - 'Thin Glass':          Nodes/Material/Derived/mtl_glass_thin.md
        - 'Liquid':              Nodes/Material/Derived/mtl_liquid.md
        - 'Metal':               Nodes/Material/Derived/mtl_metal.md
        - 'Metal (Coated)':      Nodes/Material/Derived/mtl_metal_coated.md
        - 'Plaster':             Nodes/Material/Derived/mtl_plaster.md
        - 'Plastic':             Nodes/Material/Derived/mtl_plastic.md
        - 'Plastic (Advanced)':  Nodes/Material/Derived/mtl_plastic_advanced.md
        - 'Plastic (Coated)':    Nodes/Material/Derived/mtl_plastic_coated.md
        - 'Skin':                Nodes/Material/Derived/mtl_skin.md
        - 'Translucent':         Nodes/Material/Derived/mtl_translucent.md
      - Special:
        - 'Ray Switch':          Nodes/Material/Special/mtl_ray_switch.md
        - 'Switch':              Nodes/Material/Special/mtl_switch.md
        - '2-Sided':             Nodes/Material/Special/mtl_twosided.md
    - Map:
      - Main:
        - 'Bitmap (Filetex)':    Nodes/Map/Main/map_filetex.md
        - 'Checker':             Nodes/Map/Main/map_checker.md
        - 'Falloff':             Nodes/Map/Main/map_falloff.md
        - 'Gradient':            Nodes/Map/Main/map_gradient.md
        - 'Gradient (Color)':    Nodes/Map/Main/map_gradient_color.md
        - 'Gradient (Light)':    Nodes/Map/Main/map_gradient_light.md
        - 'Grooves':             Nodes/Map/Main/map_grooves.md
        - 'Shape':               Nodes/Map/Main/map_shape.md
        - 'Tiles':               Nodes/Map/Main/map_tiles.md
      - Noise:
        - 'Brushed':             Nodes/Map/Noise/map_brushed.md
        - 'Cellular':            Nodes/Map/Noise/map_cellular.md
        - 'Dots':                Nodes/Map/Noise/map_dots.md
        - 'Flakes':              Nodes/Map/Noise/map_flakes.md
        - 'Noise':               Nodes/Map/Noise/map_noise.md
        - 'Scratches':           Nodes/Map/Noise/map_scratches.md
      - Bump:
        - 'Bump':                Nodes/Map/Bump/map_bump.md
        - 'Bump Blend':          Nodes/Map/Bump/map_bump_blend.md
        - 'Round Edges