site_name: Maverick Render Documentation
site_url: https://maverickrender.com/wp-content/docs/
copyright: (c) 2001-2017 Chema Guerra and (c) 2018-2025 RandomControl SL. All Rights Reserved.
use_directory_urls: false
nav:
  - index.md
  - CLI: CLI/index.md
  - Python:
    - Python/index.md
    - MK_api Module:
        - 'Fundamentals':               Python/Pages/python_fundamentals.md
        - 'Scene Access':               Python/Pages/python_access.md
        - 'Global Functions':           Python/Pages/python_global.md
        - 'UI Actions':                 Python/Pages/python_actions.md
    - MK_api Classes:
        - 'MK_api.mks':                 Python/Pages/MK_api_mks.md
        - 'MK_api.mtl':                 Python/Pages/MK_api_mtl.md
        - 'MK_api.map':                 Python/Pages/MK_api_map.md
        - 'MK_api.dag':                 Python/Pages/MK_api_dag.md
        - 'MK_api.node':                Python/Pages/MK_api_node.md
        - 'MK_api.img':                 Python/Pages/MK_api_img.md
        - 'MK_api.mp4':                 Python/Pages/MK_api_mp4.md
  - Tutorials:
      - UI:
          - 'UI and Layouts':           Tutorials/UI/ui_and_layout.md
          - 'UI Changes':               Tutorials/UI/ui_changes.md
          - 'IPR and Render Panel':     Tutorials/UI/ipr_render_panel.md
          - 'Attribute Editor':         Tutorials/UI/attribute_editor.md
          - 'Orbit Modes':              Tutorials/UI/orbit_modes.md
          - 'Start Page':               Tutorials/UI/start_page.md
      - Import and Objects:
          - 'Introduction':             Tutorials/Import_and_Objects/introduction.md
          - 'Import FBX Files':         Tutorials/Import_and_Objects/import_fbx_files.md
          - 'Import OBJ Files':         Tutorials/Import_and_Objects/import_obj_files.md
          - 'Merge Options':            Tutorials/Import_and_Objects/merge_options.md
          - 'Target Object':            Tutorials/Import_and_Objects/target.md
      - Cameras:
          - 'Introduction':             Tutorials/Cameras/introduction.md
          - 'Depth of Field':           Tutorials/Cameras/depth_of_field.md
      - Materials:
          - 'Introduction':             Tutorials/Materials/introduction.md
          - 'Proxy Materials':          Tutorials/Materials/proxy_materials.md
          - 'PBR':                      Tutorials/Materials/pbr.md
          - 'Round Edges':              Tutorials/Materials/round_edges.md
          - 'Shadow Catcher':           Tutorials/Materials/shadow_catcher.md
          - 'Uvmaps':                   Tutorials/Materials/uvmaps.md
          - 'Dirty/Worn':               Tutorials/Materials/dirty_worn.md
          - 'Metal Gradient Color':     Tutorials/Materials/metal_gradient_color.md
          - Displacement:
              - 'Introduction':         Tutorials/Materials/Displacement/introduction.md
              - 'Uvmaps':               Tutorials/Materials/Displacement/uvmaps.md
              - 'Zbrush':               Tutorials/Materials/Displacement/zbrush.md
              - 'Old to New':           Tutorials/Materials/Displacement/old_to_new.md
              - 'Micro-Patch':          Tutorials/Materials/Displacement/micro_patch.md
      - Lighting:
          - 'Introduction':             Tutorials/Lighting/introduction.md
          - 'Ambiences/Environments':   Tutorials/Lighting/ambiences_environments.md
          - 'Lightmixer':               Tutorials/Lighting/lightmixer.md
          - 'Projectors':               Tutorials/Lighting/projectors.md
          - 'Gradient Lights':          Tutorials/Lighting/gradient_lights.md
          - 'Lightbox':                 Tutorials/Lighting/lightbox.md
          - 'Ambiences composer':       Tutorials/Lighting/ambience_composer.md
      - Tonemap:
          - 'Introduction':             Tutorials/Tonemap/introduction.md
          - 'Lens Effects':             Tutorials/Tonemap/lens_effects.md
          - 'Custom LUTs':              Tutorials/Tonemap/custom_luts.md
          - 'Lens Improvements':        Tutorials/Tonemap/lens_improvements.md
      - Render:
          - 'Python and Batch Render':  Tutorials/Render/python_batch.md
          - 'Backplate Resolution':     Tutorials/Render/backplate_resolution.md
          - 'AOVs and Masks':           Tutorials/Render/aovs_and_masks.md
      - Render Sets:
          - 'Introduction':             Tutorials/Render_Sets/introduction.md
          - 'Update and Turntables':    Tutorials/Render_Sets/update.md
          - 'Maverick Indie':           Tutorials/Render_Sets/maverick_indie.md
          - Showcases:
              - 'Example 01':           Tutorials/Render_Sets/Showcases/example_01.md
              - 'Example 02':           Tutorials/Render_Sets/Showcases/example_02.md
              - 'Jewelry 01':           Tutorials/Render_Sets/Showcases/jewelry_01.md
              - 'Jewelry 02':           Tutorials/Render_Sets/Showcases/jewelry_02.md
      - Utils:
          - 'Surface Mode':             Tutorials/Utils/surface_mode.md
          - 'Optical Zoom':             Tutorials/Utils/optical_zoom.md
          - 'Dof Previsualization':     Tutorials/Utils/dof_previsualization.md
          - 'Lock Selection':           Tutorials/Utils/lock_selection.md
          - 'Purge':                    Tutorials/Utils/purge.md
          - 'Composition Guides':       Tutorials/Utils/composition_guides.md
          - 'IPR Canvas Overlay':       Tutorials/Utils/ipr_canvas_overlay.md
      - Trace Sets:
          - 'Introduction':             Tutorials/Trace_Sets/introduction.md
          - Showcases:
              - 'Bottles of wine':      Tutorials/Trace_Sets/Showcases/bottles.md
      - Stickers:
          - 'Introduction':             Tutorials/Stickers/introduction.md
          - Showcases:
              - 'Beats Headphones':     Tutorials/Stickers/Showcases/beats_headphones.md
              - 'Bath Bottles':         Tutorials/Stickers/Showcases/bath_bottles.md
              - 'JBL Charge3 Speakers': Tutorials/Stickers/Showcases/speakers.md
              - 'LG Xboom Go PK7':      Tutorials/Stickers/Showcases/xboom.md
      - Clone:
          - 'Introduction':             Tutorials/Clone/introduction.md
          - Showcases:
              - 'MI Band 6':            Tutorials/Clone/Showcases/mi_band.md
      - Scatter:
          - 'Introduction':             Tutorials/Scatter/introduction.md
          - 'Pattern':                  Tutorials/Scatter/pattern.md
          - Showcases:
              - 'Floating Apples':      Tutorials/Scatter/Showcases/floating_apples.md
              - 'Cosmetics':            Tutorials/Scatter/Showcases/cosmetics.md
              - 'Ganesha':              Tutorials/Scatter/Showcases/ganesha.md
              - 'Abstract Art':         Tutorials/Scatter/Showcases/abstract_art.md
      - Multi-Clone:
          - 'Introduction':             Tutorials/Multi-Clone/introduction.md
          - Showcases:
              - 'Monitor':              Tutorials/Multi-Clone/Showcases/monitor.md
              - 'Stemma Brewing':       Tutorials/Multi-Clone/Showcases/stemma_brewing.md
              - 'Lipstick':             Tutorials/Multi-Clone/Showcases/lipstick.md
      - Rhino-to-Maverick:
          - 'Workflow I':               Tutorials/Rhino_to_Maverick/workflow_1.md
          - 'Workflow II':              Tutorials/Rhino_to_Maverick/workflow_2.md
          - 'Jewelry':                  Tutorials/Rhino_to_Maverick/jewelry.md
          - 'Jewelry White Background': Tutorials/Rhino_to_Maverick/jewelry_white_background.md
      - Substance-to-Maverick:
          - 'Substance Designer':       Tutorials/Substance_to_Maverick/substance_designer.md
          - 'Substance Painter':        Tutorials/Substance_to_Maverick/substance_painter.md
          - SBSAR:
              - 'Presentation':         Tutorials/Substance_to_Maverick/SBSAR/presentation.md
              - 'Introduction':         Tutorials/Substance_to_Maverick/SBSAR/introduction.md
              - 'Example Rings':        Tutorials/Substance_to_Maverick/SBSAR/example_rings.md
      - Zbrush-to-Maverick:
          - 'Workflow':                 Tutorials/Zbrush_to_Maverick/workflow.md
      - Sketchfab-to-Maverick:
          - 'Presentation':             Tutorials/Sketchfab_to_Maverick/presentation.md
          - 'Workflow':                 Tutorials/Sketchfab_to_Maverick/workflow.md
          - 'Turntables':               Tutorials/Sketchfab_to_Maverick/turntables.md
      - ZW3D/JCD-to-Maverick:
          - 'Workflow':                 Tutorials/ZW3D_and_JCD_to_Maverick/workflow.md
      - Animation:
          - 'MOCs with Objects':        Tutorials/Animation/mocs_with_objects.md
          - 'MOCs with Cameras':        Tutorials/Animation/mocs_with_cameras.md
          - 'Exploded View':            Tutorials/Animation/exploded_view.md
          - 'Frontplate':               Tutorials/Animation/frontplate.md
          - 'Keying Materials':         Tutorials/Animation/keyframes_materials.md
          - 'Keying the Environment':   Tutorials/Animation/keyframes_environment.md
          - Showcases:
              - 'Fuji Camera Lens':     Tutorials/Animation/Showcases/fuji.md
              - 'Blaster':              Tutorials/Animation/Showcases/blaster.md
              - 'Drone':                Tutorials/Animation/Showcases/drone.md
              - 'Cosmetics':            Tutorials/Animation/Showcases/cosmetics.md
  - Nodes:
    - Global Nodes:
        - 'Globals':                   Nodes/Global Nodes/globals.md
        - 'AOVs':                      Nodes/Global Nodes/aovs.md
        - 'Tone mapping':              Nodes/Global Nodes/tonemap.md
        - 'LightMixer':                Nodes/Global Nodes/lightmixer.md
        - 'Render batcher':            Nodes/Global Nodes/batcher.md
        - 'IBL':                       Nodes/Global Nodes/ibl.md
        - 'Sky':                       Nodes/Global Nodes/sky.md
    - Cameras:
        - 'Perspective':               Nodes/Cameras/cam_persp.md
        - 'VR':                        Nodes/Cameras/cam_vr.md
    - Objects:
        - 'Assembly':                  Nodes/Objects/obj_assembly.md
        - 'Light':                     Nodes/Objects/obj_light.md
        - 'Point Cloud':               Nodes/Objects/obj_points.md
        - 'Polygon Mesh':              Nodes/Objects/obj_polymesh.md
        - 'Primitive':                 Nodes/Objects/obj_primitive.md
        - 'Target':                    Nodes/Objects/obj_target.md
    - Modifiers:
        - 'Multi-Clone':               Nodes/Modifiers/mod_multiclone.md
        - 'Scatter':                   Nodes/Modifiers/mod_scatter.md
        - 'Sticker':                   Nodes/Modifiers/mod_sticker.md
        - 'UV Map':                    Nodes/Modifiers/mod_uvmap.md
    - Materials:
      - Main:
        - 'Standard':                  Nodes/Materials/Main/mtl_standard.md
        - 'Blend':                     Nodes/Materials/Main/mtl_blend.md
        - 'Shadow Catcher':            Nodes/Materials/Main/mtl_shadow_catcher.md
      - Derived:
        - 'Emissive':                  Nodes/Materials/Derived/mtl_emissive.md
        - 'Emissive (Coated)':         Nodes/Materials/Derived/mtl_emissive_coated.md
        - 'Gemstone':                  Nodes/Materials/Derived/mtl_gemstone.md
        - 'Glass':                     Nodes/Materials/Derived/mtl_glass.md
        - 'Thin Glass':                Nodes/Materials/Derived/mtl_glass_thin.md
        - 'Liquid':                    Nodes/Materials/Derived/mtl_liquid.md
        - 'Metal':                     Nodes/Materials/Derived/mtl_metal.md
        - 'Metal (Coated)':            Nodes/Materials/Derived/mtl_metal_coated.md
        - 'Plaster':                   Nodes/Materials/Derived/mtl_plaster.md
        - 'Plastic':                   Nodes/Materials/Derived/mtl_plastic.md
        - 'Plastic (Advanced)':        Nodes/Materials/Derived/mtl_plastic_advanced.md
        - 'Plastic (Coated)':          Nodes/Materials/Derived/mtl_plastic_coated.md
        - 'Skin':                      Nodes/Materials/Derived/mtl_skin.md
        - 'Translucent':               Nodes/Materials/Derived/mtl_translucent.md
      - Special:
        - 'Ray Switch':                Nodes/Materials/Special/mtl_ray_switch.md
        - 'Switch':                    Nodes/Materials/Special/mtl_switch.md
        - '2-Sided':                   Nodes/Materials/Special/mtl_twosided.md
    - Maps:
      - Main:
        - 'Bitmap (Filetex)':          Nodes/Maps/Main/map_filetex.md
        - 'Checker':                   Nodes/Maps/Main/map_checker.md
        - 'Falloff':                   Nodes/Maps/Main/map_falloff.md
        - 'Gradient':                  Nodes/Maps/Main/map_gradient.md
        - 'Gradient (Color)':          Nodes/Maps/Main/map_gradient_color.md
        - 'Gradient (Light)':          Nodes/Maps/Main/map_gradient_light.md
        - 'Grooves':                   Nodes/Maps/Main/map_grooves.md
        - 'Shape':                     Nodes/Maps/Main/map_shape.md
        - 'Tiles':                     Nodes/Maps/Main/map_tiles.md
      - Noise:
        - 'Brushed':                   Nodes/Maps/Noise/map_brushed.md
        - 'Cellular':                  Nodes/Maps/Noise/map_cellular.md
        - 'Dots':                      Nodes/Maps/Noise/map_dots.md
        - 'Flakes':                    Nodes/Maps/Noise/map_flakes.md
        - 'Noise':                     Nodes/Maps/Noise/map_noise.md
        - 'Scratches':                 Nodes/Maps/Noise/map_scratches.md
      - Bump:
        - 'Bump':                      Nodes/Maps/Bump/map_bump.md
        - 'Bump Blend':                Nodes/Maps/Bump/map_bump_blend.md
        - 'Round Edges':               Nodes/Maps/Bump/map_round_edges.md
      - Special:
        - 'Camera Projection':         Nodes/Maps/Special/map_cam_projection.md
        - 'Color Generator':           Nodes/Maps/Special/map_colorgen.md
        - 'Composite':                 Nodes/Maps/Special/map_composite.md
        - 'Color Correction':          Nodes/Maps/Special/map_correction.md
        - 'Curvature':                 Nodes/Maps/Special/map_curvature.md
        - 'Custom IOR':                Nodes/Maps/Special/map_ior.md
        - 'Lightbox':                  Nodes/Maps/Special/map_lightbox.md
        - 'Mix':                       Nodes/Maps/Special/map_mix.md
        - 'Photometric':               Nodes/Maps/Special/map_photometric.md
        - 'Primvar':                   Nodes/Maps/Special/map_primvar.md
        - 'Ray Switch':                Nodes/Maps/Special/map_ray_switch.md
        - 'Remap':                     Nodes/Maps/Special/map_remap.md
        - 'Switch':                    Nodes/Maps/Special/map_switch.md
        - 'Triplanar':                 Nodes/Maps/Special/map_triplanar.md
        - 'User Data':                 Nodes/Maps/Special/map_user_data.md
        - 'Wireframe':                 Nodes/Maps/Special/map_wireframe.md
      - Xform:
        - '2D Xform':                  Nodes/Maps/Xform/map_xform_2d.md
        - '3D Xform':                  Nodes/Maps/Xform/map_xform_3d.md
        - 'Distortion Xform':          Nodes/Maps/Xform/map_xform_distortion.md
        - 'Spherical Xform':           Nodes/Maps/Xform/map_xform_spherical.md
      - Baked:
        - 'Baked Texture':             Nodes/Maps/Baked/map_baketex.md
        - 'Substance':                 Nodes/Maps/Baked/map_substance.md
      - Tonemap:
        - 'Glare Pattern':             Nodes/Maps/Tonemap/map_glare.md
        - 'LUT':                       Nodes/Maps/Tonemap/map_lut.md
    - Motion Controllers:
        - 'Cam Switch':                Nodes/Motion Controllers/moc_cam_switch.md
        - 'Explode':                   Nodes/Motion Controllers/moc_explode.md
        - 'Frontplate':                Nodes/Motion Controllers/moc_frontplate.md
        - 'Transform':                 Nodes/Motion Controllers/moc_transform.md
    - Programming Nodes:
      - Int:
        - 'Int':                       Nodes/Programming Nodes/Int/pro_int_value.md
        - 'Int Cast':                  Nodes/Programming Nodes/Int/pro_int_cast.md
        - 'Int (Context)':             Nodes/Programming Nodes/Int/pro_int_from_ctx.md
        - 'Int Logic':                 Nodes/Programming Nodes/Int/pro_int_logic.md
        - 'Int Math':                  Nodes/Programming Nodes/Int/pro_int_math.md
      - Float:
        - 'Float':                     Nodes/Programming Nodes/Float/pro_float_value.md
        - 'Float Cast':                Nodes/Programming Nodes/Float/pro_float_cast.md
        - 'Float (Context)':           Nodes/Programming Nodes/Float/pro_float_from_ctx.md
        - 'Float Math':                Nodes/Programming Nodes/Float/pro_float_math.md
        - 'Float Random':              Nodes/Programming Nodes/Float/pro_float_random.md
        - 'Float Remap':               Nodes/Programming Nodes/Float/pro_float_remap.md
        - 'Vector Split':              Nodes/Programming Nodes/Float/pro_vector_split.md
      - Vector:
        - 'Vector':                    Nodes/Programming Nodes/Vector/pro_vector_value.md
        - 'Vector Cast':               Nodes/Programming Nodes/Vector/pro_vector_cast.md
        - 'Vector Math':               Nodes/Programming Nodes/Vector/pro_vector_math.md
        - 'Matrix Split':              Nodes/Programming Nodes/Vector/pro_matrix_split.md
      - Matrix:
        - 'Matrix':                    Nodes/Programming Nodes/Matrix/pro_matrix_value.md
        - 'Matrix Cast':               Nodes/Programming Nodes/Matrix/pro_matrix_cast.md
        - 'Matrix (Context)':          Nodes/Programming Nodes/Matrix/pro_matrix_from_ctx.md
        - 'Matrix (Object)':           Nodes/Programming Nodes/Matrix/pro_matrix_from_obj.md
        - 'Matrix Math':               Nodes/Programming Nodes/Matrix/pro_matrix_math.md
      - Profile:
        - 'Float Profile':             Nodes/Programming Nodes/Profile/pro_float_profile.md

theme:
  name: material
  logo: assets/images/favicon.png
  features:
    - header.autohide
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.footer
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: red
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: red
      accent: blue

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 2

plugins:
  - search
  - glightbox
