site_name: Maverick Render Manual
site_url: https://maverickrender.com/
nav:
  - Home: index.md
  - About: about.md
  - Cameras:
    - 'Persp':              Cameras/persp.md
    - 'VR':                 Cameras/vr.md
  - Objects:
    - 'Assembly':           Objects/assembly.md
    - 'Assembly Light':     Objects/assembly_light.md
    - 'Curves':             Objects/curves.md
    - 'Group':              Objects/group.md
    - 'Light':              Objects/light.md
    - 'Nurbs':              Objects/nurbs.md
    - 'Points':             Objects/points.md
    - 'Polymesh':           Objects/polymesh.md
    - 'Primitive':          Objects/primitive.md
    - 'Target':             Objects/target.md
    - 'Volume':             Objects/volume.md
  - Modifiers:
    - Main:
      - 'Multiclone':       Modifiers/Main/multiclone.md
      - 'Sticker':          Modifiers/Main/sticker.md
      - 'UVmap':            Modifiers/Main/uvmap.md
    - Generator:
      - 'Fur':              Modifiers/Generator/fur.md
      - 'Pattern':          Modifiers/Generator/pattern.md
      - 'Scatter':          Modifiers/Generator/scatter.md
    - Geometry:
      - 'Mod Disp':         Modifiers/Geometry/mod_disp.md
      - 'Mod Subdiv':       Modifiers/Geometry/mod_subdiv.md
  - Materials:
    - Main:
      - 'Blend':            Materials/Main/blend.md
      - 'Shadow Catcher':   Materials/Main/shadow_catcher.md
      - 'Standard':         Materials/Main/standard.md
    - Derived:
      - 'Emissive':         Materials/Derived/emissive.md
      - 'Emissive Coated':  Materials/Derived/emissive_coated.md
      - 'Gemstone':         Materials/Derived/gemstone.md
      - 'Glass':            Materials/Derived/glass.md
      - 'Glass Thin':       Materials/Derived/glass_thin.md
      - 'Liquid':           Materials/Derived/liquid.md
      - 'Metal':            Materials/Derived/metal.md
      - 'Metal Coated':     Materials/Derived/metal_coated.md
      - 'Plaster':          Materials/Derived/plaster.md
      - 'Plastic':          Materials/Derived/plastic.md
      - 'Plastic Advanced': Materials/Derived/plastic_advanced.md
      - 'Plastic Coated':   Materials/Derived/plastic_coated.md
      - 'Skin':             Materials/Derived/skin.md
      - 'Translucent':      Materials/Derived/translucent.md
    - Special:
      - 'Cutaway':          Materials/Special/cutaway.md
      - 'Fog':              Materials/Special/fog.md
      - 'hair':             Materials/Special/hair.md
      - 'Mtl Mux':          Materials/Special/mtl_mux.md
      - 'Mtl Ray Switch':   Materials/Special/mtl_ray_switch.md
      - 'Mtl Switch':       Materials/Special/mtl_switch.md
      - 'Mtl Volume':       Materials/Special/mtl_volume.md
      - 'Twosided':         Materials/Special/twosided.md
  - Maps:
    - Main:
      - 'Checker':          Maps/Main/checker.md
      - 'Falloff':          Maps/Main/falloff.md
      - 'Filetex':          Maps/Main/filetex.md
      - 'Gradient':         Maps/Main/gradient.md
      - 'Gradient Color':   Maps/Main/gradient_color.md
      - 'Gradient Light':   Maps/Main/gradient_light.md
      - 'Shape':            Maps/Main/shape.md
      - 'Tiles':            Maps/Main/tiles.md
    - Noise:
      - 'Brushed':          Maps/Noise/brushed.md
      - 'Cellular':         Maps/Noise/cellular.md
      - 'Dots':             Maps/Noise/dots.md
      - 'Flakes':           Maps/Noise/flakes.md
      - 'Grooves':          Maps/Noise/grooves.md
      - 'Noise':            Maps/Noise/noise.md
      - 'Scratches':        Maps/Noise/scratches.md
    - Bump:
      - 'Bump':             Maps/Bump Disp/bump.md
      - 'Bump Blend':       Maps/Bump Disp/bump_blend.md
      - 'Disp':             Maps/Bump Disp/disp.md
      - 'Disp Blend':       Maps/Bump Disp/disp_blend.md
      - 'Round Edges':      Maps/Bump Disp/round_edges.md
    - Special:
      - 'Cam Projection':   Maps/Special/cam_projection.md
      - 'Colorgen':         Maps/Special/colorgen.md
      - 'Composite':        Maps/Special/composite.md
      - 'Correction':       Maps/Special/correction.md
      - 'Curvature':        Maps/Special/curvature.md
      - 'IOR':              Maps/Special/ior.md
      - 'Lightbox':         Maps/Special/lightbox.md
      - 'Mix':              Maps/Special/mix.md
      - 'Mux':              Maps/Special/mux.md
      - 'Photometric':      Maps/Special/photometric.md
      - 'Primvar':          Maps/Special/primvar.md
      - 'Ray Switch':       Maps/Special/ray_switch.md
      - 'Switch':           Maps/Special/switch.md
      - 'Triplanar':        Maps/Special/triplanar.md
      - 'User Data':        Maps/Special/user_data.md
      - 'Wireframe':        Maps/Special/wireframe.md
    - Xform:
      - 'Xform 2D':         Maps/Xform/xform_2d.md
      - 'Xform 3D':         Maps/Xform/xform_3d.md
      - 'Xform Distortion': Maps/Xform/xform_distortion.md
      - 'Xform Scattering': Maps/Xform/xform_scattering.md
      - 'Xform Spherical':  Maps/Xform/xform_spherical.md
    - Baked:
      - 'Airflow':          Maps/Baked/airflow.md
      - 'Bake':             Maps/Baked/bake.md
      - 'Substance':        Maps/Baked/substance.md
    - Tonemap:
      - 'Glare':            Maps/Tonemap/glare.md
      - 'LUT':              Maps/Tonemap/lut.md
  - Other:
    - 'AOVs':               Other/aovs.md
    - 'Globals':            Other/globals.md
    - 'IBL':                Other/ibl.md
    - 'Lightmixer':         Other/lightmixer.md
    - 'Sky':                Other/sky.md
    - 'Tonemap':            Other/tonemap.md
    
theme: readthedocs
