site_name: Maverick Render Manual
site_url: https://maverickrender.com/
nav:
  - Home: index.md
  - About: about.md
  - Camera:
      - 'Perspective': Camera/cam_persp.md
      - 'VR': Camera/cam_vr.md
  - Object:
      - 'Assembly': Object/obj_assembly.md
      - 'Light assembly': Object/obj_assembly_light.md
      - 'Curves': Object/obj_curves.md
      - '@@': Object/obj_group.md
      - 'Light': Object/obj_light.md
      - 'Point Cloud': Object/obj_points.md
      - 'Polygon Mesh': Object/obj_polymesh.md
      - 'Primitive': Object/obj_primitive.md
      - 'Target': Object/obj_target.md
  - Modifier:
      - 'Fur': Modifier/mod_fur.md
      - 'Multi-Clone': Modifier/mod_multiclone.md
      - 'Scatter': Modifier/mod_scatter.md
      - 'Sticker': Modifier/mod_sticker.md
      - 'UV Map': Modifier/mod_uvmap.md
  - Material:
      - Main:
        - 'Standard': MaterialMain/mtl_standard.md
        - 'Blend': MaterialMain/mtl_blend.md
        - 'Shadow Catcher': MaterialMain/mtl_shadow_catcher.md
        - Derived:
          - 'Emissive': MaterialDerived/mtl_emissive.md
          - 'Emissive (Coated)': MaterialDerived/mtl_emissive_coated.md
          - 'Gemstone': MaterialDerived/mtl_gemstone.md
          - 'Glass': MaterialDerived/mtl_glass.md
          - 'Thin Glass': MaterialDerived/mtl_glass_thin.md
          - 'Liquid': MaterialDerived/mtl_liquid.md
          - 'Metal': MaterialDerived/mtl_metal.md
          - 'Metal (Coated)': MaterialDerived/mtl_metal_coated.md
          - 'Plaster': MaterialDerived/mtl_plaster.md
          - 'Plastic': MaterialDerived/mtl_plastic.md
          - 'Plastic (Advanced)': MaterialDerived/mtl_plastic_advanced.md
          - 'Plastic (Coated)': MaterialDerived/mtl_plastic_coated.md
          - 'Skin': MaterialDerived/mtl_skin.md
          - 'Translucent': MaterialDerived/mtl_translucent.md
          - Special:
            - 'Fog': MaterialSpecial/mtl_fog.md
            - 'Hair': MaterialSpecial/mtl_hair.md
            - 'Multiplexor': MaterialSpecial/mtl_mux.md
            - 'Ray Switch': MaterialSpecial/mtl_ray_switch.md
            - 'Switch': MaterialSpecial/mtl_switch.md
            - '2-Sided': MaterialSpecial/mtl_twosided.md
  - Map:
      - Main:
        - 'Bitmap (Filetex)': MapMain/map_filetex.md
        - 'Checker': MapMain/map_checker.md
        - 'Falloff': MapMain/map_falloff.md
        - 'Gradient': MapMain/map_gradient.md
        - 'Gradient (Color)': MapMain/map_gradient_color.md
        - 'Gradient (Light)': MapMain/map_gradient_light.md
        - 'Grooves': MapMain/map_grooves.md
        - 'Shape': MapMain/map_shape.md
        - 'Tiles': MapMain/map_tiles.md
        - Noise:
          - 'Brushed': MapNoise/map_brushed.md
          - 'Cellular': MapNoise/map_cellular.md
          - 'Dots': MapNoise/map_dots.md
          - 'Flakes': MapNoise/map_flakes.md
          - 'Noise': MapNoise/map_noise.md
          - 'Scratches': MapNoise/map_scratches.md
          - Bump:
            - 'Bump': MapBump/map_bump.md
            - 'Bump Blend': MapBump/map_bump_blend.md
            - 'Round Edges': MapBump/map_round_edges.md
            - Special:
              - 'Camera Projection': MapSpecial/map_cam_projection.md
              - 'Color Generator': MapSpecial/map_colorgen.md
              - 'Composite': MapSpecial/map_composite.md
              - 'Color Correction': MapSpecial/map_correction.md
              - 'Curvature': MapSpecial/map_curvature.md
              - 'Custom IOR': MapSpecial/map_ior.md
              - 'Lightbox': MapSpecial/map_lightbox.md
              - 'Mix': MapSpecial/map_mix.md
              - 'Multiplexor': MapSpecial/map_mux.md
              - 'Photometric': MapSpecial/map_photometric.md
              - 'Primvar': MapSpecial/map_primvar.md
              - 'Ray Switch': MapSpecial/map_ray_switch.md
              - 'Remap': MapSpecial/map_remap.md
              - 'Switch': MapSpecial/map_switch.md
              - 'Triplanar': MapSpecial/map_triplanar.md
              - 'User Data': MapSpecial/map_user_data.md
              - 'Wireframe': MapSpecial/map_wireframe.md
              - Xform:
                - '2D Xform': MapXform/map_xform_2d.md
                - '3D Xform': MapXform/map_xform_3d.md
                - 'Distortion Xform': MapXform/map_xform_distortion.md
                - 'Scattering Xform': MapXform/map_xform_scattering.md
                - 'Spherical Xform': MapXform/map_xform_spherical.md
                - Baked:
                  - 'Airflow': MapBaked/map_airflow.md
                  - 'Baked Object': MapBaked/map_bakeobj.md
                  - 'Baked Texture': MapBaked/map_baketex.md
                  - 'Substance': MapBaked/map_substance.md
                  - Tonemap:
                    - 'Glare Pattern': MapTonemap/map_glare.md
                    - 'LUT': MapTonemap/map_lut.md
  - Programming:
      - Int:
        - 'Int': ProgrammingInt/pro_int_value.md
        - 'Int Cast': ProgrammingInt/pro_int_cast.md
        - 'Int (Context)': ProgrammingInt/pro_int_from_ctx.md
        - 'Int Logic': ProgrammingInt/pro_int_logic.md
        - 'Int Math': ProgrammingInt/pro_int_math.md
        - Float:
          - 'Float': ProgrammingFloat/pro_float_value.md
          - 'Float Cast': ProgrammingFloat/pro_float_cast.md
          - 'Float (Context)': ProgrammingFloat/pro_float_from_ctx.md
          - 'Float Math': ProgrammingFloat/pro_float_math.md
          - 'Float Random': ProgrammingFloat/pro_float_random.md
          - 'Float Remap': ProgrammingFloat/pro_float_remap.md
          - 'Vector Split': ProgrammingFloat/pro_vector_split.md
          - Vector:
            - 'Vector': ProgrammingVector/pro_vector_value.md
            - 'Vector Cast': ProgrammingVector/pro_vector_cast.md
            - 'Vector Math': ProgrammingVector/pro_vector_math.md
            - 'Vector Random': ProgrammingVector/pro_vector_random.md
            - 'Matrix Split': ProgrammingVector/pro_matrix_split.md
            - Matrix:
              - 'Matrix': ProgrammingMatrix/pro_matrix_value.md
              - 'Matrix Cast': ProgrammingMatrix/pro_matrix_cast.md
              - 'Matrix (Context)': ProgrammingMatrix/pro_matrix_from_ctx.md
              - 'Matrix (Object)': ProgrammingMatrix/pro_matrix_from_obj.md
              - 'Matrix Math': ProgrammingMatrix/pro_matrix_math.md
              - Profile:
                - 'Float Profile': ProgrammingProfile/pro_float_profile.md
                - Compound:
                  - 'Matrix Bullet': ProgrammingCompound/pro_matrix_bullet.md
  - Global:
      - 'Globals': Global/globals.md
      - 'AOVs': Global/aovs.md
      - 'Tone mapping': Global/tonemap.md
      - 'LightMixer': Global/lightmixer.md
      - 'IBL': Global/ibl.md
      - 'Sky': Global/sky.md

theme:
  name: material
  palette:
    scheme: dark
